import Head from "next/head";
import styled from "styled-components";
import Layout from "@/component/Layout";
import Seo from "@/component/Seo";
import ContentSection from "@/component/ContentSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>V-Ground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Seo title="V-Ground" />
        <ContentSection />
      </Section>
    </>
  );
}
const Section = styled.div`
  position: relative;
  width: 100%;
  height: 100vh;
  overflow-y: scroll;
  ::-webkit-scrollbar {
    display: none;
  }
`;
